### ISSUE TITLE
Multiples QUEUES

### ISSUE THREAD

**Issue by Gedehamsen021** [armandoalonso/queue#2]
like queue "events", "spells" etc

**Comment by armandoalonso** [comment]
ahh it works the same like arrays/dictionary data structures in c3. you can add multiple "Queue" objects for each of your queues

**Comment by Gedehamsen021** [comment]
but how, i can't add other Queue object in game to make this

**Comment by Gedehamsen021** [comment]
i can make a way to make like dog|cat|etc and split the separator

**Comment by armandoalonso** [comment]
ahh okay I found the issue, will be pushing an update shortly. then you should be able to add multiple queue

**Comment by armandoalonso** [comment]
https://github.com/armandoalonso/queue/releases/tag/piranha305_queue-1.0.0.1.c3addon

multiple queue are now supported, this was an oversight on my part, thanks for the bug report
